--
-- TABLES
--
drop table if exists country;
create table country (
    country_id bigint not null auto_increment,
    country_name varchar(50) not null,
    country_code2 varchar(2),
    country_code3 varchar(3),

    primary key (country_id),
    unique (country_code2),
    unique (country_code3)
) Engine=innodb;

    alter table country 
        add index idx_country__name (country_name);

    alter table country 
        add index idx_country__code2 (country_code2);
    alter table country 
        add index idx_country__code3 (country_code3);


--
-- DATA
--
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ABW','Aruba','AW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AFG','Afghanistan','AF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AGO','Angola','AO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AIA','Anguilla','AI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ALB','Albania','AL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AND','Andorra','AD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ANT','Netherlands Antilles','AN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ARE','United Arab Emirates','AE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ARG','Argentina','AR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ARM','Armenia','AM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ASM','American Samoa','AS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ATA','Antarctica','AQ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ATF','French Southern territories','TF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ATG','Antigua and Barbuda','AG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AUS','Australia','AU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AUT','Austria','AT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('AZE','Azerbaijan','AZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BDI','Burundi','BI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BEL','Belgium','BE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BEN','Benin','BJ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BFA','Burkina Faso','BF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BGD','Bangladesh','BD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BGR','Bulgaria','BG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BHR','Bahrain','BH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BHS','Bahamas','BS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BIH','Bosnia and Herzegovina','BA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BLR','Belarus','BY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BLZ','Belize','BZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BMU','Bermuda','BM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BOL','Bolivia','BO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BRA','Brazil','BR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BRB','Barbados','BB');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BRN','Brunei','BN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BTN','Bhutan','BT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BVT','Bouvet Island','BV');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('BWA','Botswana','BW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CAF','Central African Republic','CF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CAN','Canada','CA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CCK','Cocos (Keeling) Islands','CC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CHE','Switzerland','CH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CHL','Chile','CL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CHN','China','CN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CIV','Cote d\'Ivoire','CI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CMR','Cameroon','CM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('COD','Congo, The Democratic Republic of the','CD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('COG','Congo','CG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('COK','Cook Islands','CK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('COL','Colombia','CO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('COM','Comoros','KM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CPV','Cape Verde','CV');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CRI','Costa Rica','CR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CUB','Cuba','CU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CXR','Christmas Island','CX');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CYM','Cayman Islands','KY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CYP','Cyprus','CY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('CZE','Czech Republic','CZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('DEU','Germany','DE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('DJI','Djibouti','DJ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('DMA','Dominica','DM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('DNK','Denmark','DK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('DOM','Dominican Republic','DO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('DZA','Algeria','DZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ECU','Ecuador','EC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('EGY','Egypt','EG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ERI','Eritrea','ER');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ESH','Western Sahara','EH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ESP','Spain','ES');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('EST','Estonia','EE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ETH','Ethiopia','ET');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('FIN','Finland','FI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('FJI','Fiji Islands','FJ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('FLK','Falkland Islands','FK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('FRA','France','FR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('FRO','Faroe Islands','FO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('FSM','Micronesia, Federated States of','FM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GAB','Gabon','GA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GBR','United Kingdom','GB');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GEO','Georgia','GE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GHA','Ghana','GH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GIB','Gibraltar','GI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GIN','Guinea','GN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GLP','Guadeloupe','GP');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GMB','Gambia','GM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GNB','Guinea-Bissau','GW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GNQ','Equatorial Guinea','GQ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GRC','Greece','GR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GRD','Grenada','GD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GRL','Greenland','GL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GTM','Guatemala','GT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GUF','French Guiana','GF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GUM','Guam','GU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('GUY','Guyana','GY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('HKG','Hong Kong','HK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('HMD','Heard Island and McDonald Islands','HM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('HND','Honduras','HN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('HRV','Croatia','HR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('HTI','Haiti','HT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('HUN','Hungary','HU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('IDN','Indonesia','ID');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('IND','India','IN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('IOT','British Indian Ocean Territory','IO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('IRL','Ireland','IE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('IRN','Iran','IR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('IRQ','Iraq','IQ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ISL','Iceland','IS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ISR','Israel','IL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ITA','Italy','IT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('JAM','Jamaica','JM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('JOR','Jordan','JO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('JPN','Japan','JP');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KAZ','Kazakstan','KZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KEN','Kenya','KE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KGZ','Kyrgyzstan','KG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KHM','Cambodia','KH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KIR','Kiribati','KI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KNA','Saint Kitts and Nevis','KN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KOR','South Korea','KR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('KWT','Kuwait','KW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LAO','Laos','LA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LBN','Lebanon','LB');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LBR','Liberia','LR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LBY','Libyan Arab Jamahiriya','LY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LCA','Saint Lucia','LC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LIE','Liechtenstein','LI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LKA','Sri Lanka','LK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LSO','Lesotho','LS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LTU','Lithuania','LT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LUX','Luxembourg','LU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('LVA','Latvia','LV');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MAC','Macao','MO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MAR','Morocco','MA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MCO','Monaco','MC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MDA','Moldova','MD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MDG','Madagascar','MG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MDV','Maldives','MV');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MEX','Mexico','MX');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MHL','Marshall Islands','MH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MKD','Macedonia','MK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MLI','Mali','ML');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MLT','Malta','MT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MMR','Myanmar','MM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MNG','Mongolia','MN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MNP','Northern Mariana Islands','MP');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MOZ','Mozambique','MZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MRT','Mauritania','MR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MSR','Montserrat','MS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MTQ','Martinique','MQ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MUS','Mauritius','MU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MWI','Malawi','MW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MYS','Malaysia','MY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('MYT','Mayotte','YT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NAM','Namibia','NA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NCL','New Caledonia','NC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NER','Niger','NE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NFK','Norfolk Island','NF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NGA','Nigeria','NG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NIC','Nicaragua','NI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NIU','Niue','NU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NLD','Netherlands','NL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NOR','Norway','NO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NPL','Nepal','NP');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NRU','Nauru','NR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('NZL','New Zealand','NZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('OMN','Oman','OM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PAK','Pakistan','PK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PAN','Panama','PA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PCN','Pitcairn','PN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PER','Peru','PE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PHL','Philippines','PH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PLW','Palau','PW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PNG','Papua New Guinea','PG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('POL','Poland','PL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PRI','Puerto Rico','PR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PRK','North Korea','KP');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PRT','Portugal','PT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PRY','Paraguay','PY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PSE','Palestine','PS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('PYF','French Polynesia','PF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('QAT','Qatar','QA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('REU','Reunion','RE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ROM','Romania','RO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('RUS','Russian Federation','RU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('RWA','Rwanda','RW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SAU','Saudi Arabia','SA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SDN','Sudan','SD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SEN','Senegal','SN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SGP','Singapore','SG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SGS','South Georgia and the South Sandwich Islands','GS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SHN','Saint Helena','SH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SJM','Svalbard and Jan Mayen','SJ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SLB','Solomon Islands','SB');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SLE','Sierra Leone','SL');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SLV','El Salvador','SV');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SMR','San Marino','SM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SOM','Somalia','SO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SPM','Saint Pierre and Miquelon','PM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('STP','Sao Tome and Principe','ST');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SUR','Suriname','SR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SVK','Slovakia','SK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SVN','Slovenia','SI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SWE','Sweden','SE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SWZ','Swaziland','SZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SYC','Seychelles','SC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('SYR','Syria','SY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TCA','Turks and Caicos Islands','TC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TCD','Chad','TD');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TGO','Togo','TG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('THA','Thailand','TH');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TJK','Tajikistan','TJ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TKL','Tokelau','TK');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TKM','Turkmenistan','TM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TMP','East Timor','TP');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TON','Tonga','TO');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TTO','Trinidad and Tobago','TT');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TUN','Tunisia','TN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TUR','Turkey','TR');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TUV','Tuvalu','TV');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TWN','Taiwan','TW');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('TZA','Tanzania','TZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('UGA','Uganda','UG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('UKR','Ukraine','UA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('UMI','United States Minor Outlying Islands','UM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('URY','Uruguay','UY');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('USA','United States','US');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('UZB','Uzbekistan','UZ');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VAT','Holy See (Vatican City State)','VA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VCT','Saint Vincent and the Grenadines','VC');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VEN','Venezuela','VE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VGB','Virgin Islands, British','VG');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VIR','Virgin Islands, U.S.','VI');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VNM','Vietnam','VN');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('VUT','Vanuatu','VU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('WLF','Wallis and Futuna','WF');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('WSM','Samoa','WS');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('YEM','Yemen','YE');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('YUG','Yugoslavia','YU');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ZAF','South Africa','ZA');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ZMB','Zambia','ZM');
INSERT INTO `country`(country_code3,country_name, country_code2) VALUES ('ZWE','Zimbabwe','ZW');

